INSERT INTO subjects (subject, created_at, updated_at)
VALUES 
('English', NOW(), NOW()),
('Kiswahili', NOW(), NOW()),
('Creative Arts', NOW(), NOW()),
('Math', NOW(), NOW()),
('Biology', NOW(), NOW()),
('Physics', NOW(), NOW()),
('Chemistry', NOW(), NOW()),
('Social Studies', NOW(), NOW()),
('General Science', NOW(), NOW()),
('History & Government', NOW(), NOW()),
('Geography' , NOW(), NOW()),
('CRE' , NOW(), NOW()),
('IRE' , NOW(), NOW()),
('Home Science' , NOW(), NOW()),
('Art and Design' , NOW(), NOW()),
('Agriculture' , NOW(), NOW()),
('Woodwork' , NOW(), NOW()),
('Metal Work' , NOW(), NOW()),
('Building Construction' , NOW(), NOW()),
('Power Mechanics' , NOW(), NOW()),
('Electricity' , NOW(), NOW()), 
('Drawing and Design' , NOW(), NOW()),
('Aviation Technology' , NOW(), NOW()),
('Computer studies' , NOW(), NOW()),
('French' , NOW(), NOW()),
('German' , NOW(), NOW()),
('Arabic' , NOW(), NOW()),
('KSL' , NOW(), NOW()),
('Music' , NOW(), NOW()),
('Business Studies' , NOW(), NOW()),
('Pharmacy' , NOW(), NOW()),
('Computer Science' , NOW(), NOW()),
('Engineering' , NOW(), NOW()),
('Graphic Design' , NOW(), NOW()),
('Education Studies' , NOW(), NOW()),
('Economics' , NOW(), NOW()),
('Film Production' , NOW(), NOW()),
('Floristry' , NOW(), NOW()),
('Food Science' , NOW(), NOW()),
('Media and Communications' , NOW(), NOW()),
('Politics' , NOW(), NOW()), 
('Psychology' , NOW(), NOW()),
('Marketing' , NOW(), NOW()),
('Law' , NOW(), NOW()),
('Fashion Design' , NOW(), NOW()),
('Accounting & Finance', NOW(), NOW())
;
